---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-app-exchange
spec:
  schedule: "0 6,8,10,12,14 * * 1-5"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cronjob-app-exchange
        spec:
          restartPolicy: OnFailure
          containers:
            - image: mbps54/app-exchange:1.0.3
              name: cronjob-app-exchange
              env:
                - name: DB_NAME_IP
                  value: 'app-redis'
                - name: API_KEY
                  value: 'ca0cdd8c332da1840ec1e46a16ece708'
              resources:
                requests:
                  cpu: 50m
                  memory: 100Mi
                limits:
                  cpu: 100m
                  memory: 100Mi
...
