---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-app-exchange
spec:
  schedule: "0 6 1 * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cronjob-app-exchange
        spec:
          restartPolicy: OnFailure
          containers:
            - image: mbps54/app-exchange:1.1.2
              name: cronjob-app-exchange
              env:
                - name: DB_NAME_IP
                  value: 'app-redis'
                - name: API_KEY
                  value: 'Nu2Em4s1cB'
              resources:
                requests:
                  cpu: 50m
                  memory: 100Mi
                limits:
                  cpu: 100m
                  memory: 100Mi
...
