---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-web
    spec:
      containers:
        - image: mbps54/app-web:1.0.3
          imagePullPolicy: Always
          name: app-web
          ports:
            - containerPort: 8000
          env:
            - name: POST_SERVER
              valueFrom:
                secretKeyRef:
                  key: postserver
                  name: postsecrets
            - name: POST_DOMAIN
              valueFrom:
                secretKeyRef:
                  key: postdomain
                  name: postsecrets
            - name: POST_USERNAME
              valueFrom:
                secretKeyRef:
                  key: postusername
                  name: postsecrets
            - name: POST_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postpassword
                  name: postsecrets
            - name: POST_FROM_ADDRESS
              valueFrom:
                secretKeyRef:
                  key: postfromaddress
                  name: postsecrets
            - name: SERVER_NAME_IP
              value: '0.0.0.0'
            - name: DB_NAME_IP
              value: 'app-redis'
            - name: POST_TO_ADDRESS_LIST
              value: 'a.utkin@akkuyu.com'
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1000Mi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8000
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8000
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 20
          startupProbe:
            httpGet:
              path: /
              port: 8000
            failureThreshold: 20
            periodSeconds: 10
...
