name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check_yaml_syntax:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Check yaml syntax for Application
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: ./app-web/app/data

    - name: Check yaml syntax for Kubernetes
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: ./Kubernetes

  build_docker_images:
    needs: [check_yaml_syntax]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image 1
        run: cd app-web && docker build . --tag mbps54/app-web:latest

      - name: Build the Docker image 2
        run: cd app-exchange && docker build . --tag mbps54/app-exchange:latest

      - name: Create Docker Network
        run: docker network create -d bridge multi-host-network

      - name: Run Database
        run: docker run -d -p 6379:6379 --network=multi-host-network redis:latest

      - name: Run Docker image 1
        run: docker run -d -e DB_NAME_IP='redis' --network=multi-host-network mbps54/app-exchange:latest

      - name: Run Docker image 1
        run: docker run -d -p 8000:8000 -e DB_NAME_IP='redis' --network=multi-host-network mbps54/app-web:latest

#      - name: curl
#        uses: wei/curl@master
#        with:
#          args: http://localhost:8000

      - name: Login to Docker Registry
        run: docker login -u "$DOCKER_USERNAME" --password-stdin <<< "$DOCKER_PASSWORD"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image 1
        run: docker push mbps54/app-web:latest

      - name: Push Docker image 2
        run: docker push mbps54/app-exchange:latest

  deploy_on_aws:
    needs: [build_docker_images]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
                cd web_doc_app
                git pull origin master
                docker stop $(docker ps -aq)
                docker rm $(docker ps -aq)
                docker rmi $(docker images -q)
                docker pull redis:latest
                docker pull mbps54/app-exchange:latest
                docker pull mbps54/app-web:latest
                docker network create -d bridge multi-host-network
                docker run -d -p 6379:6379 --network=multi-host-network --name app-redis redis:latest
                docker run -d -e DB_NAME_IP='app-redis' -e CRON_SCHEDULE='0 9,11,13,15,17 X X 1-5' -e API_KEY='ca0cdd8c332da1840ec1e46a16ece708' --network=multi-host-network --name app-exchange mbps54/app-exchange:latest
                docker run -d -p 8000:8000 -e DB_NAME_IP='app-redis' --network=multi-host-network --name app-web mbps54/app-web:latest
